version: '3'
services:

  se:
    build:
      context: ""
      dockerfile: Dockerfile
    image: "simulation-engine"
    container_name: "se"
    volumes:
       - .:/usr/src/app/data
       #- .:/usr/src/app
        #- host_path:${CONTAINER_PATH}#this in combination with the code below does not work on windows
        #- 'tests: /usr/src/app/tests'
    #network_mode: "host"
    ports:
        - "9090:9090"
    command: ["python3", "-u", "main.py"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    # restart: "always"
    entrypoint: ["python3", "-u", "main.py"]
