version: '3'
services:
  redis:
    image: redis:latest
    container_name: "redis_S4G"
    command: redis-server
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: "always"
  ofw:
    image: garagon/optimization:amd
    container_name: "ofw"
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ./optimization-framework/prediction/resources:/usr/src/app/prediction/resources
      - ./optimization-framework/optimization/resources:/usr/src/app/optimization/resources
      - ./optimization-framework/utils/resources:/usr/src/app/utils/resources
      - ./optimization-framework/utils/gurobi/license:/usr/src/app/share/gurobi811/license/gurobi.lic
    command: ["python3", "-u", "ofw.py"]
    #restart: "always"
  se:
    build:
      context: ""
      dockerfile: Dockerfile
    image: "simulation-engine"
    container_name: "se"
    depends_on:
      - redis
    volumes:
       - ../simulation-engine/results:/usr/src/app/data
       #- .:/usr/src/app
        #- host_path:${CONTAINER_PATH}#this in combination with the code below does not work on windows
        #- 'tests: /usr/src/app/tests'
    #network_mode: "host"
    ports:
        - "9090:9090"
    command: ["python3", "-u", "main.py"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    # restart: "always"
    entrypoint: ["python3", "-u", "main.py"]
